name: "workflow-hello-world"
# This is a simple GitHub Actions workflow that runs on push to the master branch

on:
    push:
            
jobs:
    hello_world:
        runs-on: ubuntu-latest
        steps:
            - name: Say Hello
              run: echo "Hello, world!"
              




